### ISSUE TITLE
attribute routing gives exception

### ISSUE THREAD

**Issue by joriszwart** [techvice/ErrorHandlerMvc#2]
I ran into an issue when I enabled attribute routing. At start up the application gives an exception. Is it possible to use ErrorHandlerMVC with attribute routing?

#### Exception Details ####

    System.ArgumentException: Cannot create a descriptor for instance method 'Void Execute(System.Web.Routing.RequestContext)'
      on type 'ErrorHandlerMvc.InternalErrorController' because the type does not derive from ControllerBase.
    Parameter name: methodInfo

Source error:

    Line 15:             routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
    Line 16: 
    Line 17:             routes.MapMvcAttributeRoutes();        // excepts here
    Line 18:             routes.LowercaseUrls = true;
Source file: `Source File: ./Global.asax.cs    Line: 17`

#### Stack trace ####

    [ArgumentException: Cannot create a descriptor for instance method 'Void Execute(System.Web.Routing.RequestContext)' on type 'ErrorHandlerMvc.InternalErrorController' because the type does not derive from ControllerBase.
    Parameter name: methodInfo]
       System.Web.Mvc.ReflectedActionDescriptor..ctor(MethodInfo methodInfo, String actionName, ControllerDescriptor controllerDescriptor, Boolean validateMethod) +336
       System.Web.Mvc.ReflectedActionDescriptor..ctor(MethodInfo methodInfo, String actionName, ControllerDescriptor controllerDescriptor) +45
       System.Web.Mvc.Async.<>c__DisplayClass4.<GetActionDescriptorDelegate>b__2(String actionName, ControllerDescriptor controllerDescriptor) +73
       System.Web.Mvc.Routing.AttributeRoutingMapper.GetActionDescriptors(ReflectedAsyncControllerDescriptor controller) +240
       System.Web.Mvc.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, IEnumerable`1 controllerTypes, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +201
       System.Web.Mvc.Routing.AttributeRoutingMapper.MapAttributeRoutes(RouteCollection routes, IEnumerable`1 controllerTypes, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +333
       System.Web.Mvc.Routing.AttributeRoutingMapper.MapAttributeRoutes(RouteCollection routes, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +398
       System.Web.Mvc.Routing.AttributeRoutingMapper.MapAttributeRoutes(RouteCollection routes, IInlineConstraintResolver constraintResolver) +192
       System.Web.Mvc.RouteCollectionAttributeRoutingExtensions.MapMvcAttributeRoutes(RouteCollection routes) +123
       SampleApp.MvcApplication.RegisterRoutes(RouteCollection routes) in ./Global.asax.cs:17
       SampleApp.MvcApplication.Application_Start() in ./Global.asax.cs:33

    [HttpException (0x80004005): Cannot create a descriptor for instance method 'Void Execute(System.Web.Routing.RequestContext)' on type 'ErrorHandlerMvc.InternalErrorController' because the type does not derive from ControllerBase.
    Parameter name: methodInfo]
       System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9936485
       System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
       System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
       System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
       System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

    [HttpException (0x80004005): Cannot create a descriptor for instance method 'Void Execute(System.Web.Routing.RequestContext)' on type 'ErrorHandlerMvc.InternalErrorController' because the type does not derive from ControllerBase.
    Parameter name: methodInfo]
       System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9950728
       System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
       System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

## Reproduction ##

I can reproduce this issue by putting this in *SampleApp.RegisterRoutes()* in the current version (d.d. 22 January 2015)

    routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
    routes.MapMvcAttributeRoutes();        // <-- this line is added

**Comment by joriszwart** [comment]
Is deriving `InternalErrorController` from `ControllerBase` an option? At (a very) first glance it seems to work, but I cannot back it up with test results for all cases.

**Comment by techvice** [comment]
Quite right on the ControllerBase. I'm making adjustments now. @joriszwart

**Comment by joriszwart** [comment]
So I guess it is fixed in 3dc6690
