### ISSUE TITLE
Exceptions in views are not handled nicely

### ISSUE THREAD

**Issue by joriszwart** [techvice/ErrorHandlerMvc#3]
When an exception occurs in a view a yellow-screen-of-death is shown with the exception that is thrown.
## Reproduction

Put these lines in the view:

```
@{
    throw new Exception("exception in view");
}
```

**Comment by techvice** [comment]
Been a goal to get this working since the beginning. I'm trying to tackle the issue today.

**Comment by joriszwart** [comment]
Adding `<customErrors mode="On">` or `<customErrors mode="RemoteOnly">` to `web.config` results in friendly _ErrorHandlerMVC_ messages.

However I can not foresee whether this has bad consequences. I easily get lost in the forest of error-related settings of IIS/ASP.NET

**Comment by techvice** [comment]
Thanks @joriszwart. I'm unfamiliar with the consequences of the configuration change myself. I'll look more into what that means. I appreciate your assistance with this!

**Comment by joriszwart** [comment]
Any progress with this?

**Comment by techvice** [comment]
No. I reviewed it back in June and tried to compare my project to the original but I wasn't able to narrow it down. I hope to be able to get time to work on the issues in the next month or so.

**Comment by joriszwart** [comment]
Lets close it :-)
